### ISSUE TITLE
When running the lab this error occurs during the CI process.

### ISSUE THREAD

**Issue by amccaskill** [hashicorp/learn-terraform-circleci#14]
╷
│ Error: Unsupported Terraform Core version
│ 
│   on main.tf line 8, in terraform:
│    8:     required_version = "~> 3.22.0"
│ 
│ This configuration does not support Terraform version 1.0.0. To proceed, either choose another supported Terraform version or update this version constraint. Version constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

**Comment by im2nguyen** [comment]
Hi @amccaskill, the above PR should address the error you're running into.

tldr, we need to bump the AWS provider version to the latest version 😄

**Comment by amccaskill** [comment]
Thanks I appreciate it. 
:)
