### ISSUE TITLE
Update using CircleCI 2.1 syntax?

### ISSUE THREAD

**Issue by jamescrowley** [hashicorp/learn-terraform-circleci#2]
It would be fab if you could provide a version of this example using the CircleCI 2.1 syntax. I think this would simplify your example a fair bit - as I don't think you'd need all the YAML merging maps type 'magic' any more.

**Comment by tr0njavolta** [comment]
Thanks for your feedback! I will review those changes. This guide has been updated for simplicity, so please [check it out on Learn](https://learn.hashicorp.com/tutorials/terraform/circle-ci)
