### ISSUE TITLE
Line missing in code snippet

### ISSUE THREAD

**Issue by Jac2NL** [hashicorp/learn-terraform-circleci#4]
```
pip install --user awscli
export PATH="~/.local/bin:$PATH"
git clone https://github.com/hashicorp/learn-terraform-circleci/ .
pwd
aws s3 sync --acl public-read "/home/circleci/project/assets" s3://${APP_BUCKET}
```

In case people are wondering where that "assets" directory comes from: 
the git clone line is missing in the [learn.hashicorp.com tutorial](https://learn.hashicorp.com/terraform/development/circle).

**Comment by tr0njavolta** [comment]
Thanks for your feedback! I'm closing as this refers to an older version of the tutorial. If you would like to review that, [check it out on Learn](https://learn.hashicorp.com/tutorials/terraform/circle-ci).
